plugins {
    id 'java'
    id 'application'
}

group = 'com.darkona'
version = '0.0.1'
repositories {
    mavenCentral()
}

jar {
    archiveBaseName = 'tardigrade'
    manifest {
        attributes 'Main-Class': 'com.darkona.tardigrade.Main'
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    dependsOn 'copyResources'
}
application {
    mainClass = 'com.darkona.tardigrade.Main'
}

dependencies {
    implementation 'ch.qos.logback:logback-classic:1.5.19'
    implementation 'ch.qos.logback:logback-core:1.5.19'
    implementation 'org.slf4j:slf4j-api:2.0.7'
    implementation 'commons-cli:commons-cli:1.3.1'
    implementation 'org.fusesource.jansi:jansi:2.4.1'
    implementation 'org.yaml:snakeyaml:2.6'
}

tasks.register('copyResources', Copy) {
    from 'src/main/resources'
    into 'build/libs'

}
